### PR TITLE
Front-end Validation

### PR DESCRIPTION
**Pull request by slattery-mark**
Performs front-end form validation using the Chain of Responsibility design pattern

Progress toward [NR #10](https://github.com/WSU-4110/Eventsly/issues/53) and [NR #11](https://github.com/WSU-4110/Eventsly/issues/54)

Additionally, the create event page is styled & has form validation

### CODE REVIEW

**Review by CarbonatedSoftDrink — DISMISSED** [review]
Looks good, from what i understand.

**Comment by slattery-mark** [comment]
Just noticed that there is some sort of bug with the way latitude and longitude are being sent to the DB. Must have been something I missed when I refactored the original create event scripts into the map decorator. Let's hold off on pulling this until I have it fixed.

**Review by CarbonatedSoftDrink — APPROVED** [review]
double checked the event creation, the long/lat is more accurate now (stores more decimal digits). data is still the same on the registration page. login page still errors on incorrect data and logs me in on correct data.

**Review by cj-fox — APPROVED** [review]
Everything looks good and tests well.

**Pull request merged**
