### PR TITLE
Feature/dashboard

### PR DESCRIPTION
**Pull request by cj-fox**
Satisfies FR12. Delete Account, FR16. Dashboard, FR17. Delete Event.

Created dashboard. Dashboard shows 'My Events' table. Each entry in the table shows same information as the bookmarks page shows.  Each event in the table also has a link to the Full Details page, and a button to delete the event.

The dashboard also has a link to delete the user's account.

### CODE REVIEW

**Review by DStawicki-fq4252 — COMMENTED** [review]
The code works well for the Dashboard event implementation. I tested an event on an account, and it was not in the other user's dashboard. 

However, upon pressing delete account, it does in fact delete the account, but it doesn't force the user out of their account. This allows them to technically stay logged in even though the website will be broken since they are not in the userlist. 

This can be fixed I am sure, with forcing the logout to run upon hitting the delete account button.

**Comment by CarbonatedSoftDrink** [comment]
Going to wait on that delete account fix before approving.

**Comment by cj-fox** [comment]
> The code works well for the Dashboard event implementation. I tested an event on an account, and it was not in the other user's dashboard.
> 
> However, upon pressing delete account, it does in fact delete the account, but it doesn't force the user out of their account. This allows them to technically stay logged in even though the website will be broken since they are not in the userlist.
> 
> This can be fixed I am sure, with forcing the logout to run upon hitting the delete account button.

Changes have been implemented.

**Review by DStawicki-fq4252 — APPROVED** [review]
Works as intended now. Logs out upon deletion. Great fix.

**Review by CarbonatedSoftDrink — APPROVED** [review]
file changes look good. code looks good.

**Pull request merged**
